"""
Kaggle Integration — Browse, download, and benchmark deepfake datasets.

Provides helpers for:
- Listing curated deepfake detection datasets from Kaggle
- Downloading datasets via the Kaggle API
- Benchmarking the loaded model against a dataset folder
"""

import os
import logging
from pathlib import Path

logger = logging.getLogger(__name__)

# ── Pre-configured deepfake datasets ─────────────────────────
DATASETS = [
    {
        "slug": "xhlulu/140k-real-and-fake-faces",
        "name": "140K Real and Fake Faces",
        "description": "A large-scale dataset containing 140,000 images — 70K real faces from the Flickr dataset and 70K fake faces generated by StyleGAN. Ideal for binary classification tasks.",
        "size": "2.1 GB",
        "samples": "140,000",
        "tags": ["StyleGAN", "Binary Classification", "Large Scale"],
        "icon": "fa-face-smile",
    },
    {
        "slug": "ciplab/real-and-fake-face-detection",
        "name": "Real and Fake Face Detection",
        "description": "Curated dataset from CIPLab with high-quality real and manipulated face images. Includes various manipulation techniques with different difficulty levels.",
        "size": "588 MB",
        "samples": "1,288",
        "tags": ["Face Manipulation", "Quality Levels", "Research"],
        "icon": "fa-magnifying-glass",
    },
    {
        "slug": "manjilkarki/deepfake-and-real-images",
        "name": "Deepfake and Real Images",
        "description": "A balanced dataset of deepfake and real images designed for training and evaluating deepfake detection models. Well-organized train/test split.",
        "size": "830 MB",
        "samples": "~2,000",
        "tags": ["Balanced", "Train/Test Split", "Beginner Friendly"],
        "icon": "fa-images",
    },
    {
        "slug": "dagnelies/deepfake-faces",
        "name": "Deepfake Faces",
        "description": "Collection of AI-generated deepfake faces alongside real photographs. Features diverse manipulation methods for robust model evaluation.",
        "size": "1.2 GB",
        "samples": "~10,000",
        "tags": ["Diverse Methods", "Evaluation", "Faces"],
        "icon": "fa-user-secret",
    },
    {
        "slug": "hamzafarooqi/deepfake-detection-challenge-face-crops",
        "name": "DFDC Face Crops",
        "description": "Face crops extracted from the Facebook Deepfake Detection Challenge. Pre-processed and ready for direct model training and evaluation.",
        "size": "4.5 GB",
        "samples": "~100,000",
        "tags": ["Facebook DFDC", "Pre-cropped", "Competition"],
        "icon": "fa-crop-simple",
    },
]


def get_datasets() -> list:
    """Return the curated list of datasets with download status."""
    datasets = []
    for ds in DATASETS:
        ds_copy = ds.copy()
        folder_name = ds["slug"].replace("/", "_")
        ds_copy["folder_name"] = folder_name
        ds_copy["downloaded"] = os.path.exists(
            os.path.join("datasets", folder_name)
        )
        datasets.append(ds_copy)
    return datasets


def is_kaggle_configured() -> bool:
    """Check if the Kaggle API credentials are set up."""
    kaggle_json = os.path.expanduser("~/.kaggle/kaggle.json")
    kaggle_json_win = os.path.join(os.environ.get("USERPROFILE", ""), ".kaggle", "kaggle.json")
    env_user = os.environ.get("KAGGLE_USERNAME")
    env_key = os.environ.get("KAGGLE_KEY")

    return (
        os.path.exists(kaggle_json)
        or os.path.exists(kaggle_json_win)
        or (env_user and env_key)
    )


def download_dataset(slug: str) -> dict:
    """
    Download a Kaggle dataset by its slug.

    Returns:
        dict with keys: success (bool), message (str), path (str or None)
    """
    if not is_kaggle_configured():
        return {
            "success": False,
            "message": "Kaggle API not configured. Place kaggle.json in ~/.kaggle/ or set KAGGLE_USERNAME and KAGGLE_KEY environment variables.",
            "path": None,
        }

    try:
        from kaggle.api.kaggle_api_extended import KaggleApi

        api = KaggleApi()
        api.authenticate()

        folder_name = slug.replace("/", "_")
        target_dir = os.path.join("datasets", folder_name)
        os.makedirs(target_dir, exist_ok=True)

        logger.info("📥 Downloading dataset: %s → %s", slug, target_dir)
        api.dataset_download_files(slug, path=target_dir, unzip=True)

        return {
            "success": True,
            "message": f"Dataset '{slug}' downloaded successfully!",
            "path": target_dir,
        }

    except ImportError:
        return {
            "success": False,
            "message": "kaggle package not installed. Run: pip install kaggle",
            "path": None,
        }
    except Exception as e:
        logger.error("Dataset download error: %s", e)
        return {
            "success": False,
            "message": f"Download failed: {str(e)}",
            "path": None,
        }


def benchmark_model(dataset_dir: str, processor, model) -> dict:
    """
    Run the deepfake detection model against images in a dataset folder.
    Expects sub-folders named 'real' and 'fake' (case-insensitive).

    Returns a dict with accuracy, precision, recall, and per-image results.
    """
    import torch
    from PIL import Image

    results = {"total": 0, "correct": 0, "predictions": []}

    # Find real/fake subfolders
    real_dir = None
    fake_dir = None

    for item in os.listdir(dataset_dir):
        item_lower = item.lower()
        item_path = os.path.join(dataset_dir, item)
        if os.path.isdir(item_path):
            if "real" in item_lower:
                real_dir = item_path
            elif "fake" in item_lower or "deepfake" in item_lower or "synthetic" in item_lower:
                fake_dir = item_path

    # Also search one level deeper
    if not real_dir or not fake_dir:
        for item in os.listdir(dataset_dir):
            sub = os.path.join(dataset_dir, item)
            if os.path.isdir(sub):
                for child in os.listdir(sub):
                    child_lower = child.lower()
                    child_path = os.path.join(sub, child)
                    if os.path.isdir(child_path):
                        if "real" in child_lower and not real_dir:
                            real_dir = child_path
                        elif ("fake" in child_lower or "deepfake" in child_lower) and not fake_dir:
                            fake_dir = child_path

    if not real_dir and not fake_dir:
        return {
            "success": False,
            "message": "Could not find 'real' and 'fake' subdirectories in the dataset.",
            "accuracy": 0,
        }

    image_exts = {".jpg", ".jpeg", ".png", ".bmp", ".webp"}

    def process_folder(folder, true_label, limit=100):
        if not folder:
            return
        files = [
            f for f in os.listdir(folder)
            if os.path.splitext(f)[1].lower() in image_exts
        ][:limit]  # Limit to avoid long waits

        for fname in files:
            fpath = os.path.join(folder, fname)
            try:
                image = Image.open(fpath).convert("RGB")
                inputs = processor(images=image, return_tensors="pt")
                with torch.no_grad():
                    outputs = model(**inputs)
                probs = torch.softmax(outputs.logits, dim=1)
                predicted = torch.argmax(probs).item()
                confidence = probs[0][predicted].item()

                pred_label = "REAL IMAGE" if predicted == 0 else "DEEPFAKE IMAGE"
                is_correct = (pred_label == true_label)

                results["total"] += 1
                if is_correct:
                    results["correct"] += 1

                results["predictions"].append({
                    "file": fname,
                    "true_label": true_label,
                    "predicted": pred_label,
                    "confidence": round(confidence, 4),
                    "correct": is_correct,
                })
            except Exception as e:
                logger.warning("Skipping %s: %s", fname, e)

    process_folder(real_dir, "REAL IMAGE")
    process_folder(fake_dir, "DEEPFAKE IMAGE")

    total = results["total"]
    correct = results["correct"]

    # Calculate metrics
    tp = sum(1 for p in results["predictions"] if p["true_label"] == "DEEPFAKE IMAGE" and p["predicted"] == "DEEPFAKE IMAGE")
    fp = sum(1 for p in results["predictions"] if p["true_label"] == "REAL IMAGE" and p["predicted"] == "DEEPFAKE IMAGE")
    fn = sum(1 for p in results["predictions"] if p["true_label"] == "DEEPFAKE IMAGE" and p["predicted"] == "REAL IMAGE")

    precision = tp / (tp + fp) if (tp + fp) > 0 else 0
    recall = tp / (tp + fn) if (tp + fn) > 0 else 0
    f1 = 2 * precision * recall / (precision + recall) if (precision + recall) > 0 else 0

    return {
        "success": True,
        "message": f"Benchmarked {total} images",
        "total": total,
        "correct": correct,
        "accuracy": round(correct / total * 100, 2) if total else 0,
        "precision": round(precision * 100, 2),
        "recall": round(recall * 100, 2),
        "f1_score": round(f1 * 100, 2),
        "predictions": results["predictions"][:20],  # Return first 20 for display
    }
